#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
echo "› brew bundle"
brew bundle

# Sublime 3
echo "> Now open Sublime. Tools -> Install Package Control. Shift + cmd + p -> 'install' and install the 'Glacier' theme. Quit Sublime"
echo "> Press enter when done."
read enter

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
